---
- name: Add Volume to Volume group ibm storage virualize
  hosts: localhost
  vars_files:
    - vars.yml
  
  tasks:
    - name: Create a volume group


    - name: Create a volume group with snapshot policy

    


