---
- name: Add Volume to Volume group ibm storage virualize
  hosts: localhost
  vars_files:
    - vars.yml
  
  tasks:
    - name: Create a volume group
      # Content suggestion provided by Ansible Lightspeed
      ibm.spectrum_virtualize.ibm_svc_manage_volumegroup:
        clustername: "{{ _clustername_ }}"
        domain: "{{ _domain_ }}"
        username: "{{ _username_ }}"
        password: "{{ _password_ }}"
        log_path: /tmp/playbook.debug
        name: "{{ _name_ }}"
        state: present

    - name: Create a volume group with snapshot policy
      # Content suggestion provided by Ansible Lightspeed
      ibm.spectrum_virtualize.ibm_svc_manage_volumegroup:
        clustername: "{{ _clustername_ }}"
        domain: "{{ _domain_ }}"
        username: "{{ _username_ }}"
        password: "{{ password }}"
        log_path: /tmp/playbook.debug
        name: "{{ _name_ }}"
        state: present
        snapshotpolicy: "{{ _snapshotpolicy_ }}"