---
- name: Create volume to ibm spectrum virtualize
  hosts: localhost
  vars:
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
    clustername: "{{ _clustername_ }}"
    volumegroup:
      name: vg_test_ansible
      pool: POOL_FS7200_TOP
      snapshotpolicy: "snapshotpolicy_ansible"
      replicationpolicy: "PBR"

  vars_files:
    - vars.yml

  tasks:

    - name: Create volume group with snapshotpolicy and replicationpolicy using vars volumegroup
    
    


