---
- name: Create volume to ibm spectrum virtualize
  hosts: localhost
  vars:
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
    clustername: "{{ _clustername_ }}"
    namevolume: volume_group_ansible
    size: 1
    unit: gb
    volumegroup: vg_test_ansible
    pool: POOL_FS7200_TOP

  vars_files:
    - vars.yml

  tasks:
    - name: Create volume into volumegroup using vars
